# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
array_1d = np.array([3])

# Create a 2-dimensional NumPy array using np.array()
array_2d = np.array([2,3])

# Create a 3-dimensional Numpy array using np.array()
array_3d = np.array([1,2,3])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1d.shape,array_1d.size,array_1d.ndim

((1,), 1, 1)

In [6]:
# Attributes of 2-dimensional array
array_2d.shape,array_2d.size,array_2d.ndim

((2,), 2, 1)

In [7]:
# Attributes of 3-dimensional array
array_3d.shape,array_3d.size,array_3d.ndim

((3,), 3, 1)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
dataframe_1 = pd.DataFrame(array_1d)
dataframe_1

,0
0,3


In [11]:
# Create an array of shape (10, 2) with only ones
array_1s = np.ones([10,2])
array_1s

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros([7,2,3])
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
step1 = np.arange(0,100,1)
step1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

randarr1 = np.random.randint(10,size=(7,2))
randarr1

array([[1, 9],
       [5, 8],
       [8, 4],
       [0, 7],
       [4, 0],
       [7, 2],
       [0, 2]], dtype=int32)

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_logistical = np.random.rand(3,5)
random_logistical

array([[0.98244121, 0.98973357, 0.8774551 , 0.95461409, 0.00176543],
       [0.63757779, 0.88905393, 0.94047526, 0.13279164, 0.93554792],
       [0.15166174, 0.80628135, 0.01733943, 0.34087525, 0.07803089]])

In [25]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
randarr_10 = np.random.randint(0,10,size=(4,6))
randarr_10

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?
they're the same
Are the numbers in the array different or the same? Why do think this is?

pythons pseudo-random number generator is generatic the same values with seed set to the same number


In [26]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

var_arr = np.random.randint(1,11,size=(3,7))
# Find the unique numbers in the array you just created
np.unique(var_arr)

array([ 1,  2,  3,  4,  5,  7,  9, 10], dtype=int32)

In [27]:
# Find the 0'th index of the latest array you created
var_arr[0]

array([ 9,  1, 10,  3,  7,  4,  9], dtype=int32)

In [31]:
# Get the first 2 rows of latest array you created
var_arr,var_arr[:2,:]

(array([[ 9,  1, 10,  3,  7,  4,  9],
        [ 3,  5,  3,  7,  5,  9,  7],
        [ 2,  4,  9,  2, 10,  9, 10]], dtype=int32),
 array([[ 9,  1, 10,  3,  7,  4,  9],
        [ 3,  5,  3,  7,  5,  9,  7]], dtype=int32))

In [32]:
# Get the first 2 values of the first 2 rows of the latest array
var_arr[:2,:2]

array([[9, 1],
       [3, 5]], dtype=int32)

In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
randarr010 = np.random.randint(0,11,size=(3,5))
randones010 = np.ones([3,5])
randarr010,print('\n'),randones010

(array([[10,  4,  9,  6,  9],
        [ 8,  6,  8,  7,  1],
        [ 0,  6,  6,  7,  4]], dtype=int32),
 None,
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [42]:
# Add the two arrays together
most_recent = np.add(randarr010,randones010)

In [43]:
# Create another array of ones of shape (5, 3)
randones_new = np.ones([5,3])

In [44]:
# Try add the array of ones and the other most recent array together
np.add(randones_new,most_recent)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
transopse or reshape them

In [45]:
# Create another array of ones of shape (3, 5)
another_ones = np.ones([3,5])

In [48]:
# Subtract the new array of ones from the other most recent array
latest = np.subtract(most_recent,another_ones)
latest

array([[10.,  4.,  9.,  6.,  9.],
       [ 8.,  6.,  8.,  7.,  1.],
       [ 0.,  6.,  6.,  7.,  4.]])

In [49]:
# Multiply the ones array with the latest array
latest = np.multiply(another_ones,latest)
latest

array([[10.,  4.,  9.,  6.,  9.],
       [ 8.,  6.,  8.,  7.,  1.],
       [ 0.,  6.,  6.,  7.,  4.]])

In [50]:
# Take the latest array to the power of 2 using '**'
latest = np.square(latest)
latest

array([[100.,  16.,  81.,  36.,  81.],
       [ 64.,  36.,  64.,  49.,   1.],
       [  0.,  36.,  36.,  49.,  16.]])

In [51]:
# Do the same thing with np.square()
latest**2

array([[1.000e+04, 2.560e+02, 6.561e+03, 1.296e+03, 6.561e+03],
       [4.096e+03, 1.296e+03, 4.096e+03, 2.401e+03, 1.000e+00],
       [0.000e+00, 1.296e+03, 1.296e+03, 2.401e+03, 2.560e+02]])

In [52]:
# Find the mean of the latest array using np.mean()
np.mean(latest)

np.float64(44.333333333333336)

In [53]:
# Find the maximum of the latest array using np.max()
np.max(latest)

np.float64(100.0)

In [54]:
# Find the minimum of the latest array using np.min()
np.min(latest)

np.float64(0.0)

In [55]:
# Find the standard deviation of the latest array
np.std(latest)

np.float64(28.672092509771396)

In [56]:
# Find the variance of the latest array
float(np.var(latest))

822.088888888889

In [57]:
# Reshape the latest array to (3, 5, 1)
latest = latest.reshape(3,5,1)
latest

array([[[100.],
        [ 16.],
        [ 81.],
        [ 36.],
        [ 81.]],

       [[ 64.],
        [ 36.],
        [ 64.],
        [ 49.],
        [  1.]],

       [[  0.],
        [ 36.],
        [ 36.],
        [ 49.],
        [ 16.]]])

In [58]:
# Transpose the latest array
latest=latest.T
latest

array([[[100.,  64.,   0.],
        [ 16.,  36.,  36.],
        [ 81.,  64.,  36.],
        [ 36.,  49.,  49.],
        [ 81.,   1.,  16.]]])

What does the transpose do?
changes axes with each other 0 = n, 1 = n-1 etc

In [59]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_two_one = np.random.randint(0,10,size=(3,3))
arr_two_two = np.random.randint(0,10,size=(3,2))
arr_two_one,arr_two_two

(array([[2, 7, 5],
        [2, 0, 2],
        [4, 2, 0]], dtype=int32),
 array([[4, 9],
        [6, 6],
        [8, 9]], dtype=int32))

In [60]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_two_one,arr_two_two)


array([[ 90, 105],
       [ 24,  36],
       [ 28,  48]], dtype=int32)

In [61]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_randint1 = np.random.randint(0,10,size=(4,3))
arr_randint2 = np.random.randint(0,10,size=(4,3))

In [62]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_randint1,arr_randint2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [63]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr_randint1,arr_randint2.T)

array([[101, 110,  81,  84],
       [ 30,  27,  45,  18],
       [ 80,  86, 102,  68],
       [ 39,  58,  75,  60]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?
because dot product need the same number of entries in a row of one matrix as in the column of the other 
Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [64]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_randint1 = np.random.randint(0,10,size=(4,3))
arr_randint2 = np.random.randint(0,10,size=(4,3))

In [65]:
# Compare the two arrays with '>'
arr_randint1>arr_randint2

array([[False, False,  True],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

What happens when you compare the arrays with `>`?
it compares them element by element

In [40]:
# Compare the two arrays with '>='


In [69]:
# Find which elements of the first array are greater than 7
arr_randint1 = (arr_randint1>7)
arr_randint1

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [70]:
# Which parts of each array are equal? (try using '==')
arr_randint1 = np.random.randint(0,10,size=(4,3))
arr_randint2 = np.random.randint(0,10,size=(4,3))
arr_randint1 == arr_randint2

array([[False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [72]:
# Sort one of the arrays you just created in ascending order
arr_randint1.sort()
arr_randint1

array([[0, 1, 2],
       [0, 4, 7],
       [0, 0, 1],
       [1, 5, 6]], dtype=int32)

In [73]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr_randint1)


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [75]:
# Find the index with the maximum value in one of the arrays you've created
arr_randint1,np.argmax(arr_randint1)

(array([[0, 1, 2],
        [0, 4, 7],
        [0, 0, 1],
        [1, 5, 6]], dtype=int32),
 np.int64(5))

In [76]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr_randint1)

np.int64(0)

In [77]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr_randint1,axis=1)

array([2, 2, 2, 2])

In [78]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr_randint1,axis=0)

array([0, 2, 2])

In [80]:
# Create an array of normally distributed random numbers
normal_random = np.random.randn(2,2)
normal_random

array([[ 0.79103195, -0.90938745],
       [ 1.40279431, -1.40185106]])

In [81]:
# Create an array with 10 evenly spaced numbers between 1 and 100
array = np.linspace(1,100,10)
array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.